import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const [{ schema }] = JSON.parse(await readFile(join(here, 'schema.snapshot.json'), 'utf8'));
const [{ grants }] = JSON.parse(await readFile(join(here, 'grants.snapshot.json'), 'utf8'));

const ident = (value) => `"${String(value).replaceAll('"', '""')}"`;
const literal = (value) => `'${String(value).replaceAll("'", "''")}'`;
const tableRef = (schemaName, table) => `${ident(schemaName)}.${ident(table)}`;
const sections = [
  '-- Generated by generate-schema.mjs from the sanitized local schema snapshots. DO NOT apply outside local test Supabase.\n',
  'BEGIN;\n',
  'CREATE SCHEMA IF NOT EXISTS public;\nCREATE SCHEMA IF NOT EXISTS extensions;\n',
];

// Supabase supplies auth.uid(), auth.users, storage.objects and the platform roles/schemas.
// Install only extensions reported by the snapshot; plpgsql is a PostgreSQL built-in.
for (const extension of schema.extensions ?? []) {
  if (extension.name === 'plpgsql') continue;
  if (!/^[a-z_][a-z0-9_-]*$/i.test(extension.name) || !/^[a-z_][a-z0-9_]*$/i.test(extension.schema)) {
    throw new Error(`Unexpected extension identifier: ${extension.name}/${extension.schema}`);
  }
  sections.push(`CREATE SCHEMA IF NOT EXISTS ${ident(extension.schema)};`);
  sections.push(`CREATE EXTENSION IF NOT EXISTS ${ident(extension.name)} WITH SCHEMA ${ident(extension.schema)};`);
}

for (const table of schema.tables) {
  const columns = schema.columns.filter((column) => column.table === table.name);
  if (!columns.length) throw new Error(`No columns in snapshot for ${table.name}`);
  const defs = columns.map((column) => {
    const pieces = [ident(column.name), column.type];
    if (column.generated) throw new Error(`Generated expression for ${table.name}.${column.name} is not present in the sanitized snapshot; refusing to guess.`);
    else if (column.identity) {
      const seq = schema.sequences?.find((entry) => entry.name === `${table.name}_${column.name}_seq`);
      if (seq) {
        const attrs = [`START WITH ${seq.start}`, `INCREMENT BY ${seq.increment}`, `CACHE ${seq.cache}`, seq.cycle ? 'CYCLE' : 'NO CYCLE'];
        if (seq.min !== 1) attrs.push(`MINVALUE ${seq.min}`);
        pieces.push(`GENERATED ${column.identity === 'a' ? 'ALWAYS' : 'BY DEFAULT'} AS IDENTITY (${attrs.join(' ')})`);
      } else pieces.push(`GENERATED ${column.identity === 'a' ? 'ALWAYS' : 'BY DEFAULT'} AS IDENTITY`);
    } else if (column.default !== null && column.default !== undefined) pieces.push(`DEFAULT ${column.default}`);
    if (column.notnull) pieces.push('NOT NULL');
    return `  ${pieces.join(' ')}`;
  });
  sections.push(`CREATE TABLE ${tableRef('public', table.name)} (\n${defs.join(',\n')}\n);`);
}

const constraintOrder = { p: 0, u: 1, c: 2, f: 3, x: 4 };
for (const constraint of [...(schema.constraints ?? [])].sort((a, b) => (constraintOrder[a.type] ?? 9) - (constraintOrder[b.type] ?? 9))) {
  sections.push(`ALTER TABLE ${tableRef('public', constraint.table)} ADD CONSTRAINT ${ident(constraint.name)} ${constraint.definition};`);
}
for (const index of schema.indexes ?? []) sections.push(`${index.replace(/;?$/, ';')}`);

for (const fn of schema.functions ?? []) {
  // Definitions are preserved from pg_get_functiondef after audit; schema must be public.
  if (!fn.definition.startsWith('CREATE OR REPLACE FUNCTION public.')) throw new Error(`Unexpected function schema: ${fn.name}`);
  sections.push(fn.definition.trim().replace(/;?$/, ';'));
}
for (const trigger of schema.triggers ?? []) {
  if (trigger.schema !== 'public' || !trigger.definition.startsWith('CREATE TRIGGER ')) throw new Error(`Unexpected trigger: ${trigger.name}`);
  sections.push(trigger.definition.trim().replace(/;?$/, ';'));
}

for (const table of schema.tables) {
  if (!/^[a-z_][a-z0-9_]*$/i.test(table.name)) throw new Error(`Unexpected table name: ${table.name}`);
  if (table.rls) sections.push(`ALTER TABLE ${tableRef('public', table.name)} ENABLE ROW LEVEL SECURITY;`);
  if (table.force_rls) sections.push(`ALTER TABLE ${tableRef('public', table.name)} FORCE ROW LEVEL SECURITY;`);
}

for (const policy of schema.policies ?? []) {
  if (!['public', 'storage'].includes(policy.schemaname)) throw new Error(`Unexpected policy schema: ${policy.schemaname}`);
  if (!/^[a-z_][a-z0-9_]*$/i.test(policy.tablename)) throw new Error(`Unexpected policy table: ${policy.tablename}`);
  const roles = (policy.roles ?? []).map((role) => role === 'public' ? 'PUBLIC' : ident(role)).join(', ') || 'PUBLIC';
  let sql = `CREATE POLICY ${ident(policy.policyname)} ON ${tableRef(policy.schemaname, policy.tablename)} AS ${policy.permissive} FOR ${policy.cmd} TO ${roles}`;
  if (policy.qual) sql += ` USING (${policy.qual})`;
  if (policy.with_check) sql += ` WITH CHECK (${policy.with_check})`;
  sections.push(`${sql};`);
}

const safeRoles = new Set(['anon', 'authenticated', 'service_role']);
const grouped = new Map();
for (const grant of grants) {
  if (!safeRoles.has(grant.role) || grant.schema !== 'public' || !['r', 'S'].includes(grant.kind)) throw new Error(`Unexpected ACL record: ${JSON.stringify(grant)}`);
  const objectKind = grant.kind === 'r' ? 'TABLE' : 'SEQUENCE';
  const key = `${objectKind}|${grant.name}|${grant.role}|${Boolean(grant.grantable)}`;
  grouped.set(key, [...(grouped.get(key) ?? []), grant.privilege]);
}
for (const [key, privileges] of grouped) {
  const [kind, name, role, grantable] = key.split('|');
  const unique = [...new Set(privileges)].sort();
  sections.push(`GRANT ${unique.join(', ')} ON ${kind} ${tableRef('public', name)} TO ${ident(role)}${grantable === 'true' ? ' WITH GRANT OPTION' : ''};`);
}

// Bucket definitions are data in Supabase Storage's local metadata table.
for (const bucket of schema.buckets ?? []) {
  const allowed = bucket.allowed_mime_types === null ? 'NULL' : `ARRAY[${bucket.allowed_mime_types.map(literal).join(', ')}]::text[]`;
  const limit = bucket.file_size_limit === null ? 'NULL' : String(bucket.file_size_limit);
  sections.push(`INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES (${literal(bucket.id)}, ${literal(bucket.name)}, ${bucket.public}, ${limit}, ${allowed}) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public, file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;`);
}
sections.push('COMMIT;\n');
await writeFile(join(here, 'schema.sql'), `${sections.join('\n\n')}\n`);
console.log(`Wrote schema.sql (${schema.tables.length} tables, ${schema.constraints.length} constraints, ${schema.policies.length} policies).`);
